---
title: "Making Visualizations with Cal Enviroscreen"
author: "Lyndsay Miles"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#libraries
library(tidyverse)
library(readxl)
library(kableExtra)
library(reactable)
```

Data extracted from OEHHA, https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40, "CalEnviroScreen 4.0 Excel and Data Dictionary PDF"

```{r, echo=FALSE, include=FALSE, warning=FALSE}
enviro <- read_excel("data/calenviroscreen40resultsdatadictionary_F_2021.xlsx", sheet = 1, na = "---") 
demog <- read_excel("data/calenviroscreen40resultsdatadictionary_F_2021.xlsx", sheet = 2, na = "---") 
#view(data)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE}
#removed first row which states "Demographic data (total population, age groups and race/ethnicity) by census tract were extracted from the 2019 American Community Survey."
demog_clean <- demog %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE)))%>%
  rename(county=californiacounty)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#demographics by county
demog_clean_county <- demog_clean %>%
  group_by(county) %>% 
  summarize(totalpop = sum(totalpopulation),
            avg_children = mean(`children<10years(%)`),
            avg_10_64 = mean(`pop10-64years(%)`),
            avg_elderly = mean(`elderly>64years(%)`),
            avg_hispanic = mean(`hispanic(%)`),
            avg_white = mean(`white(%)`),
            avg_black = mean(`africanamerican(%)`),
            avg_aian = mean(`nativeamerican(%)`),
            avg_asian = mean(`asianamerican(%)`),
            avg_other = mean(`other/multiple(%)`))%>%
  arrange(desc(totalpop))
```

```{r, echo=FALSE, warning=FALSE}
#in table format
kable(demog_clean_county,
      booktabs = T,
      caption = "Demographics by California County") %>%
  footnote(general = "OEHHA",
           general_title = "Data Source") %>%
  kable_styling(full_width = T)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#clean data
enviro_clean <- enviro %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE)))%>%
  rename(county=californiacounty) %>% 
  mutate(lowbirthweight = as.numeric(lowbirthweight),
         education = as.numeric(education),
         linguisticisolation = as.numeric(linguisticisolation),
         unemployment = as.numeric(unemployment),
         housingburden = as.numeric(housingburden)) #%>%
  #drop_na(`ces4.0score`)
  
#I only drop NA values for ces4.0 score. 1965 NA values before drop, 720 remain
#review of other missing values: counties with no NAs for lowbirthweight (29); education (42), linguisticisolation (15), unemployment (12), housing (37), poverty (57). Only 5 counties have a complete data set for the chosen variables after dropping NAs for ces4.0score
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#enviro_clean grouped by county
enviro_clean_county <- enviro_clean %>%
  group_by(county)%>%
  summarize(totalpop = sum(totalpopulation),
            #avg_ces_score = weighted.mean(`ces4.0score`, weight),
            avg_pollutionburden = weighted.mean(pollutionburden, totalpopulation, na.rm=T),
            avg_asthma = weighted.mean(asthma, totalpopulation, na.rm = T),
            avg_lowbirthweight = weighted.mean(lowbirthweight, totalpopulation, na.rm=T),
            avg_cvd = weighted.mean(cardiovasculardisease, totalpopulation, na.rm=T),
            avg_education = weighted.mean(education, totalpopulation, na.rm=T),
            avg_lingisolation = weighted.mean(linguisticisolation, totalpopulation, na.rm=T),
            avg_poverty = weighted.mean(poverty, totalpopulation, na.rm = T),
            avg_unemployment = weighted.mean(unemployment, totalpopulation, na.rm=T),
            avg_housingburden = weighted.mean(housingburden, totalpopulation, na.rm=T)
            )
```

```{r, echo=FALSE} 
kable(enviro_clean_county,
      booktabs = T,
      caption = "Selected Health Concerns, related Environmental and Social Factors, by California County") %>%
  footnote(general = "OEHHA",
           general_title = "Data Source") %>%
  kable_styling(full_width = T)

#note - total population in demog_clean_county and enviro_clean_county are not the same. For example, LA county in demog_clean_county is 10081570 and in enviro_clean_county it is 10040912. This is due to the removal of NA values I think
```



```{r, echo=FALSE, include=FALSE, warning=FALSE}
#Explore asthma and related risk factors & associated illness

enviro_clean_asthma <- enviro_clean %>%
  select(county, totalpopulation, `ces4.0score`, `pm2.5`, dieselpm, pesticides, traffic, pollutionburden, asthma, cardiovasculardisease, poverty, housingburden) %>% 
  group_by(county) %>% 
  summarize(totalpop = sum(totalpopulation), 
            #avg_ces_score = round(weighted.mean(`ces4.0score`, weight),2),
            avg_pm2.5 = round(weighted.mean(`pm2.5`, totalpopulation),2),
            avg_diesel = round(weighted.mean(dieselpm, totalpopulation),2),
            avg_pesticides = round(weighted.mean(pesticides, totalpopulation),2),
            avg_traffic = round(weighted.mean(traffic, totalpopulation),2),
            avg_pollutionburden = round(weighted.mean(pollutionburden, totalpopulation),2),
            avg_asthma = round(weighted.mean(asthma, totalpopulation),2),
            avg_cvd = round(weighted.mean(cardiovasculardisease, totalpopulation),2),
            avg_poverty = round(weighted.mean(poverty, totalpopulation),2)
            )
```

```{r}
reactable(enviro_clean_asthma)
```


