---
title: "Making Visualizations with Cal Enviroscreen"
author: "Lyndsay Miles"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#libraries
library(tidyverse)
library(readxl)
library(kableExtra)
library(reactable)
library(ggplot2)
library(plotly)
```

Data extracted from OEHHA, https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40, "CalEnviroScreen 4.0 Excel and Data Dictionary PDF"

```{r, echo=FALSE, include=FALSE, warning=FALSE}
enviro <- read_excel("data/calenviroscreen40resultsdatadictionary_F_2021.xlsx", sheet = 1, na = "---") 
demog <- read_excel("data/calenviroscreen40resultsdatadictionary_F_2021.xlsx", sheet = 2, na = "---") 
#view(data)
```


```{r, echo=FALSE, include=FALSE, warning=FALSE}
#clean data
enviro_clean <- enviro %>% 
  rename_with( ~ tolower(gsub(" ", "", .x, fixed = TRUE)))%>%
  rename(county=californiacounty) %>% 
  select(censustract, totalpopulation, county, longitude, latitude, `ces4.0score`, `ces4.0percentile`, poverty)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
#Which counties have the highest ces4.0 scores? 
#enviro_clean grouped by county
enviro_clean_county <- enviro_clean %>%
  group_by(county)%>%
  summarize(totalpop = sum(totalpopulation),
            avg_ces_score = weighted.mean(`ces4.0score`, totalpopulation, na.rm = T),
            avg_poverty = weighted.mean(poverty, totalpopulation, na.rm = T)
            )

kable(enviro_clean_county,
      booktabs = T,
      caption = "CES 4.0 Score by County") %>%
  footnote(general = "OEHHA",
           general_title = "Data Source") %>%
  kable_styling(full_width = T)
```

```{r, echo=FALSE} 
#how much is poverty associated with ces4.0 score? 
ggplot(data=enviro_clean_county, aes(x=avg_ces_score, y=avg_poverty))+
  geom_point()+
  geom_smooth()
```


```{r}
#does ces score associate with a county's rural status?
#https://www.rcrcnet.org/counties
rural_counties <- c("Alpine", "Amador", "Butte", "Calaveras", "Colusa", 
                    "Del Norte", "El Dorado", "Glenn", "Humboldt", "Imperial", 
                    "Inyo", "Kings", "Lake", "Lassen", "Madera", 
                    "Mariposa", "Mendocino", "Merced", "Modoc", "Mono", 
                    "Monterey", "Napa", "Nevada", "Placer", "Plumas", 
                    "San Benito", "San Luis Obispo", "Santa Barbara", "Shasta", 
                    "Sierra", "Siskiyou", "Solano", "Sonoma", "Sutter", 
                    "Tehama", "Trinity", "Tulare", "Tuolumne", "Yolo",
                    "Yuba")
```

```{r}
enviro_clean_rural <- enviro_clean %>% 
  group_by(county)%>% 
  summarize(avg_ces_score_co = weighted.mean(`ces4.0score`, totalpopulation, na.rm = T),
            avg_poverty_co = weighted.mean(poverty, totalpopulation, na.rm = T)
                            )   %>%
  mutate(rural = if_else(county %in% rural_counties, "rural", "not rural"))%>%
  arrange(rural, desc(avg_ces_score_co), desc(avg_poverty_co))
enviro_clean_rural$rural <- as.factor(enviro_clean_rural$rural)
```


```{r}
rural_plot_1 <- ggplot(enviro_clean_rural, aes(x=rural, y=avg_ces_score_co)) +
  geom_boxplot() +
  labs(title = "Distribution of ces4.0 scores by rural county status") 

ggplotly(rural_plot_1)

#consider removing outliers (40+) from rural counties
```

```{r}
rural_plot_2 <- ggplot(enviro_clean_rural, aes(x=rural, y=avg_poverty_co)) +
  geom_boxplot() +
  labs(title = "Distribution of poverty by rural county status") 

ggplotly(rural_plot_2)
```


```{r}
rural_plot_3 <- ggplot(data=enviro_clean_rural, aes(x=avg_ces_score_co, y= avg_poverty_co, color=rural, label=county))+
  geom_point()+
  geom_smooth()
#more difference among counties that are non-rural. there is less difference in rural areas ces scores across counties.

ggplotly(rural_plot_3)
```

